import {
  ChartBar,
  Gear,
  Package,
  Drop,
  Receipt,
  Truck,
  UserList,
  FileText,
  ChefHat,
  Storefront,
  UsersThree,
  ClipboardText,
  QrCode,
  CalendarCheck,
  Clock,
  Timer,
  HandCoins,
  IdentificationBadge,
  AddressBook,
  Gift,
  Money,
  Megaphone,
  CreditCard,
} from "@phosphor-icons/react";

// Every screen has a permission key; Owners hold them all. `always` screens are open to every signed-in person.

export const APP_NAV_ITEMS = [
  { path: "/dashboard", label: "Dashboard", icon: Storefront, group: "Main", permission: "dashboard", module: "restaurant", feature: "reports" },
  { path: "/reservations", label: "Reservations", icon: CalendarCheck, group: "Main", permission: "reservations", module: "restaurant", feature: "tables" },
  { path: "/qr-management", label: "QR", icon: QrCode, group: "Main", permission: "qr_management", module: "restaurant", feature: "tables" },
  { path: "/manager", label: "Manager", icon: UsersThree, group: "Role Screens", permission: "manager_view", module: "restaurant", feature: "reports" },
  { path: "/waiter", label: "Waiter", icon: ClipboardText, group: "Role Screens", permission: "waiter_view", module: "restaurant", feature: "tables" },
  { path: "/chef", label: "Chef", icon: ChefHat, group: "Role Screens", permission: "kitchen_view", module: "restaurant", feature: "kot" },
  { path: "/time-clock", label: "Time Clock", icon: Timer, group: "Role Screens", always: true },
  { path: "/billing", label: "Billing", icon: Receipt, group: "Main", permission: "billing", module: "restaurant", feature: "billing" },
  { path: "/central-kitchen", label: "Central Kitchen", icon: Truck, group: "Main", permission: "central_kitchen", module: "restaurant", feature: "inventory" },
  { path: "/inventory", label: "Inventory", icon: Drop, group: "Main", permission: "inventory", module: "restaurant", feature: "inventory" },
  { path: "/reports", label: "Reports", icon: ChartBar, group: "Main", permission: "reports", module: "restaurant", feature: "reports" },
  { path: "/products", label: "Products", icon: Package, group: "Manage", permission: "products", module: "restaurant", feature: "products" },
  { path: "/price-rules", label: "Happy Hours", icon: Clock, group: "Manage", permission: "price_rules", module: "restaurant", feature: "products" },
  { path: "/bills", label: "Bills", icon: FileText, group: "Manage", permission: "bills", module: "restaurant", feature: "billing" },
  { path: "/staff", label: "Staff", icon: UserList, group: "Manage", permission: "staff", module: "restaurant", feature: "staff" },
  { path: "/attendance", label: "Attendance", icon: IdentificationBadge, group: "Manage", permission: "attendance" },
  { path: "/tips", label: "Tips", icon: HandCoins, group: "Manage", permission: "tips" },
  { path: "/customers", label: "Customers", icon: AddressBook, group: "Manage", permission: "customers" },
  { path: "/gift-cards", label: "Gift Cards", icon: Gift, group: "Manage", permission: "gift_cards" },
  { path: "/payroll", label: "Payroll", icon: Money, group: "Manage", permission: "payroll" },
  { path: "/marketing", label: "Marketing", icon: Megaphone, group: "Manage", permission: "marketing" },
  { path: "/settings", label: "Settings", icon: Gear, group: "System", permission: "settings" },
  { path: "/plan", label: "Plan & Billing", icon: CreditCard, group: "System", ownerOnly: true },
];
